import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/style/globals.css'
import Header from '@/components/Layout/Header'
import { GeistSans } from 'geist/font/sans';
import Footer from '@/components/Layout/Footer';
//import { GeistMono } from 'geist/font/mono';


export const metadata: Metadata = {
  title: 'NFT Landing',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
